version: '3.8'

services:
  backend:
    build: .
    container_name: bitespeed_backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: npm run dev # Runs the server in dev mode, you can change this to npm start for production

  postgres:
    image: postgres:14
    container_name: bitespeed_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      DB_PORT: ${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
